# Generated by Django 4.1.7 on 2023-03-27 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
