# Generated by Django 4.1.7 on 2023-03-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='work_status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('overtime', 'Overtime'), ('halfday', 'Half Day')], max_length=10, null=True),
        ),
    ]
