# Generated by Django 4.1.7 on 2023-03-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_timerecord_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='work_status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('undertime', 'Undertime'), ('overtime', 'Overtime'), ('halfday', 'Half Day')], max_length=20, null=True),
        ),
    ]
