# Generated by Django 4.1.7 on 2023-04-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_additioanl_deductions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additioanl_Deductions',
            new_name='Additional_Deductions',
        ),
    ]
