# Generated by Django 4.1.7 on 2023-04-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_additioanl_deductions_additional_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='overtime_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='overtime_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='additional_deductions',
            name='late_tardiness',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='additional_deductions',
            name='no_of_holiday',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='additional_deductions',
            name='overtime',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='additional_deductions',
            name='sss',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
