# Generated by Django 4.1.7 on 2023-03-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_totalpresent_time_record_alter_totalpresent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalpresent',
            name='time_record',
        ),
    ]
